[project]
name = "learn-ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-adk>=1.21.0",
    "litellm>=1.80.11",
    "openai>=2.7.1",
    "protobuf==5.28.1",
]
